import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Suspense } from "react";
import Layout from "@/Components/Layout/Layout";
import { PopupContextProvider } from "@/Components/Store/PopupContext";
import { NotificationContextProvider } from "@/Components/Store/NotificationContext";
import { ProgressContextProvider } from "@/Components/Store/ProgressContext";
import { getPublicData } from "@/Components/helpers/getPublicData";
import { ITextContent } from "@/Components/Admin/TextContent/AdminManageTextContentPage";
import { LocaleContextProvider } from "@/Components/Store/LocaleContext";

const font = localFont({
  src: "./fonts/IRANYekanXVFaNumVF.woff",
  variable: "--fontFa",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface ISite {
  textContent?: ITextContent;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const site = await getPublicData<ISite>("site");

  return (
    <html lang="fa" dir="rtl">
      <body className={font.variable}>
        <Suspense fallback={<Layout>{children}</Layout>}>
          <LocaleContextProvider value={{ textContent: site?.textContent }}>
            <ProgressContextProvider>
              <NotificationContextProvider>
                <PopupContextProvider>
                  <Layout>{children}</Layout>
                </PopupContextProvider>
              </NotificationContextProvider>
            </ProgressContextProvider>
          </LocaleContextProvider>
        </Suspense>
      </body>
    </html>
  );
}
