import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Layout from "@/Components/Layout/Layout";
import { PopupContextProvider } from "@/Components/Store/PopupContext";
import { NotificationContextProvider } from "@/Components/Store/NotificationContext";
import { ProgressContextProvider } from "@/Components/Store/ProgressContext";
import { BreadCrumpContextProvider } from "@/Components/Store/BreadCrumpStore";
import { SockectContextProvider } from "@/Components/Store/SocketContext";
import LocaleScopeProvider from "@/Components/Store/LocaleScopeProvider";
import { getScopedTextContent } from "@/Components/helpers/getScopedTextContent";
import { ContentNamespace } from "@/Components/Enums/contentNamespaces";

const font = localFont({
  src: "./fonts/IRANYekanXVFaNumVF.woff",
  variable: "--fontFa",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  applicationName: "NoyanAI",
  manifest: "/manifest.json",
  // app/favicon.ico is picked up automatically by Next; these add the
  // modern/high-res variants alongside it.
  icons: {
    icon: [
      { url: "/icons/icon.svg", type: "image/svg+xml" },
      { url: "/icons/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/icons/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/favicon-48x48.png", sizes: "48x48", type: "image/png" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [
      { url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
  appleWebApp: {
    capable: true,
    title: "NoyanAI",
    statusBarStyle: "default",
  },
};

export const viewport: Viewport = {
  themeColor: "#1a80e5",
};

// Text content for the app chrome that <Layout> renders around every page:
// "common" (public header/footer, mobile menu, user/cart/notification
// buttons, auth popups, ...) and "layoutPanel" (dashboard/panel shell and
// sidebars). Fetched here, server-side, so the chrome is in the initial HTML.
// The root layout persists across client-side navigations, so this is only
// fetched once per full page load — pages fetch just their own namespaces.
const CHROME_NS: ContentNamespace[] = ["common", "layoutPanel"];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const chromeTextContent = await getScopedTextContent(CHROME_NS);

  // No <Suspense> around the tree: it used to be here only because
  // ProgressContextProvider called useSearchParams(), and its fallback
  // (<Layout> without any providers) is what reached the initial HTML —
  // header/footer with no text content. useSearchParams now lives in its own
  // small Suspense boundary inside ProgressContextProvider instead.
  return (
    <html lang="fa" dir="rtl">
      <body className={font.variable}>
        <LocaleScopeProvider
          namespaces={CHROME_NS}
          initialTextContent={chromeTextContent}
        >
          <ProgressContextProvider>
            <NotificationContextProvider>
              <PopupContextProvider>
                <BreadCrumpContextProvider>
                  <SockectContextProvider>
                    <Layout>{children}</Layout>
                  </SockectContextProvider>
                </BreadCrumpContextProvider>
              </PopupContextProvider>
            </NotificationContextProvider>
          </ProgressContextProvider>
        </LocaleScopeProvider>
      </body>
    </html>
  );
}
