import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Suspense } from "react";
import Layout from "@/Components/Layout/Layout";
import { PopupContextProvider } from "@/Components/Store/PopupContext";
import { NotificationContextProvider } from "@/Components/Store/NotificationContext";
import { ProgressContextProvider } from "@/Components/Store/ProgressContext";

const font = localFont({
  src: "./fonts/IRANYekanXVFaNumVF.woff",
  variable: "--fontFa",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={font.variable}>
        <Suspense fallback={<Layout>{children}</Layout>}>
          <ProgressContextProvider>
            <NotificationContextProvider>
              <PopupContextProvider>
                <Layout>{children}</Layout>
              </PopupContextProvider>
            </NotificationContextProvider>
          </ProgressContextProvider>
        </Suspense>
      </body>
    </html>
  );
}
