const contentKeys = [
  "homePage",
  "officeBook",
  "medicalConsult",
  "phoneConsult",
  "textConsult",
  "aiDetection",
  "blog",
  "forDoctors",
  "login",
  "male",
  "female",
  "medicalSystemTitle",
  "medicalSystemCode",
  "specialities",
  "province",
  "city",
  "address",
  "description",
  "online",
  "dashboard",
  "financialMangement",
  "toman",
  "secrataries",
  "bookingCalendar",
  "patients",
  "licenses",
  "clinics",
  "phrmaciesAndLabs",
  "insurances",
  "offers",
  "discounts",
  "articles",
  "chatWithPatients",
  "drugsAndPrescriptions",
  "patientDocuments",
  "logout",
  "buyLicense",
  "currentLicense",
  "deposit",
  "currentBalance",
  "doctorClinics",
  "doctorJoinClinics",
  "clinicAdditionRequests",
  "clinicsList",
  "clinicName",
  "department",
  "noDepartment",
  "actions",
  "newItem",
  "joinClinicRequest",
  "nothingFound",
  "clickToRequestAddClinic",
  "message",
  "submitRequest",
  "loading",
  "checkInput",
  "submittedAt",
  "submissionParty",
  "doctor",
  "clinic",
  "status",
  "Pending",
  "Approved",
  "Rejected",
  "statusLastChangedAt",
  "resubmitJoinClinicRequestConfirmationMessage",
  "leaveClinicConfirmationMessage",
  "clinicAddress",
  "ownerPhone",
  "Proccessing",
  "Done",
  "ownerName",
  "cancel",
  "submit",
] as const;

export type ContentKey = (typeof contentKeys)[number];

// const locations = ["header", "general", "doctorPanel"] as const;

// export type Location = (typeof locations)[number];

// export const locationMap: Record<ContentKey, Location> = {
//   aiDetection: "header",
//   blog: "header",
//   forDoctors: "header",
//   homePage: "header",
//   login: "header",
//   medicalConsult: "header",
//   officeBook: "header",
//   phoneConsult: "header",
//   textConsult: "header",
//   female: "general",
//   male: "general",
//   medicalSystemTitle: "doctorPanel",
//   medicalSystemCode: "doctorPanel",
//   specialities: "doctorPanel",
//   province: "general",
//   city: "general",
//   address: "general",
// };
