import { ContentKey } from "./contentKeys";

// Groups of ContentKeys that a given page/section actually needs.
//
// This is additive to contentKeys.tsx (which stays the single source of
// truth for every valid key) — it does not replace or change it. A key can
// appear in more than one namespace if it's genuinely shared.
//
// Filled in page by page as they get migrated (home, doctorsList,
// diseasesList, drugsList, symptomsList so far). The rest of the ~1200 keys
// still get grouped the same way, one page/section at a time.
export const contentNamespaces = {
  // Keys used by sitewide chrome (header/footer/shared UI) that most pages
  // end up needing regardless of what namespace they belong to. Grows as
  // more pages get migrated and their shared components' keys turn up here
  // (BreadCrump, Pagination, and the generic Components/UI/ListPage/*
  // pieces reused across the disease/drug/symptom/etc. list pages).
  common: [
    "loading",
    "cancel",
    "submit",
    "close",
    "back",
    "confirm",
    "yes",
    "no",
    "home",
    "online",
    "previousPage",
    "nextPage",
    "results",
    "all",
    "seeDetails",
    "generatedByAi",
    "dataIsnotAccurate",
    "showPackagesOnly",
  ],

  // Every key actually referenced by Components/Home/*.tsx (HomeHero,
  // HomeSpecialities, HomeServices, HomePopular, HomeAds, HomeRegister,
  // HomeIntroduction), found by grepping their getContent(...) calls.
  home: [
    "homeHeroTitle",
    "homeHeroLegend",
    "chatWithAi",
    "reserveABooking",
    "homeChatLegend",
    "aiInputPlaceholder",
    "homeAiExamplesLegend",
    "noyanIntroductionTitle",
    "noyanIntroductionLegend",
    "mostViewedSpecialities",
    "seeAll",
    "greatest",
    "goToPage",
    "HomeAdTitle",
    "homeAdSubtitle",
    "homeAdDescription",
    "onlineBooking",
    "popularDoctors",
    "noyanClinicalServicesTitle",
    "noyanClinicalServicesDescription",
    "seeAllClinicalServices",
    "bestCliniclaServices",
    "registerTitle",
    "registerDescription",
    "registerDoctorsAndClinics",
    "weHaveTooManyUsers",
  ],

  // app/doctors/page.tsx + app/doctors/[page]/page.tsx (DoctorsListPage,
  // DoctorCard, DoctorCardWithSessions).
  doctorsList: [
    "doctors",
    "noName",
    "availableSessionCount",
    "moreSessions",
    "doctorNotAvailableMessage",
  ],

  // app/disease/page.tsx (DiseasesListPage + DiseaseCard).
  diseasesList: [
    "diseasesListTitle",
    "diseasesListLegend",
    "diseasesListIntroTitle",
    "diseasesListIntroDescription",
    "searchInDiseases",
    "nSymptoms",
    "nRecommendedDrugs",
  ],

  // app/drug/page.tsx (DrugsListPage + DrugCard).
  drugsList: [
    "drugsListTitle",
    "drugsListLegend",
    "drugsListIntroTitle",
    "drugsListIntroDescription",
    "searchInDrugs",
    "dosage",
  ],

  // app/symptom/page.tsx (SymptomsListPage + SymptomCard).
  symptomsList: [
    "symptomsListTitle",
    "symptomsListLegend",
    "symptomsListIntroTitle",
    "symptomsListIntroDescription",
    "searchInSymptoms",
  ],

  // app/dashboard/page.tsx — the logged-in user's dashboard landing page
  // (DashboardPage: UserIdentity, UserVitals, UserMedicalDetails, and their
  // edit popups EditUserDetailsPopup/MutateUserMedicalPopup/AddVitalPopup).
  // No hardcoded strings found here — this tree was already fully wired to
  // contentKeys.
  dashboardHome: [
    "user",
    "name",
    "notAssigned",
    "nationalId",
    "gender",
    "male",
    "female",
    "dateOfBirth",
    "username",
    "noData",
    "vitals",
    "vitalHistory",
    "medicalDetails",
    "bloodType",
    "height",
    "weight",
    "addVitalTitle",
    "bloodOxygen",
    "bloodPressure",
    "bodyTemperature",
    "heartRate",
    "checkInput",
  ],

  // app/dashboard/invoice/page.tsx + [nodeId] (DashboardManageInvoice(s)Page,
  // CheckoutPopup — CheckoutPopup itself has no getContent calls).
  dashboardInvoice: [
    "submittedAt",
    "total",
    "paymentStatus",
    "actions",
    "paid",
    "notPaid",
    "status",
    "toman",
    "createdAt",
    "pay",
  ],

  // app/dashboard/booking/page.tsx + [nodeId] (DashboardManageBooking(s)Page).
  // Also fixed a hardcoded "عملیات" table-column label here (the sibling
  // invoice table used getContent("actions") correctly; this one didn't).
  dashboardBooking: [
    "reserveUser",
    "doctor",
    "sessionDate",
    "sessionStart",
    "sessionEnd",
    "office",
    "sessionType",
    "submittedAt",
    "actions",
    "patientName",
    "bookingPrice",
    "toman",
    "textChat",
    "sipCall",
    "voiceCall",
    "videoCall",
    "inPerson",
  ],

  // app/dashboard/vital/page.tsx (DashboardManageVitalsPage + VitalList).
  dashboardVital: [
    "vitals",
    "addVitals",
    "createdAt",
    "doctor",
    "bloodOxygen",
    "bloodPressure",
    "bodyTemperature",
    "heartRate",
  ],

  // app/dashboard/notification/page.tsx (DashboardNotificationsPage).
  dashboardNotification: [
    "markAsRead",
    "notifications",
    "unreadOnly",
    "markAllAsRead",
    "noNotificationsYet",
  ],

  // app/dashboard/support/page.tsx + [nodeId] (SupportPage, TicketPage,
  // SubmitTicketPopup). Includes the ticketSubject*/*Ticket status keys,
  // which are looked up dynamically via ticketSubjectContentKeyDict /
  // ticketStatusesContentKeyDict rather than as string literals.
  dashboardSupport: [
    "support",
    "newTicket",
    "visitTicket",
    "nothingWasFound",
    "closeTicket",
    "missingMessageErrorMessage",
    "writeYourMessage",
    "sendMessage",
    "backToList",
    "noMessagesYet",
    "ticketClosedNotice",
    "ticketSubject",
    "ticketTitle",
    "ticketMessage",
    "ticketSubjectAccount",
    "ticketSubjectBilling",
    "ticketSubjectBug",
    "ticketSubjectFeature",
    "ticketSubjectGeneral",
    "ticketSubjectTech",
    "closedTicket",
    "inProgressTicket",
    "openTicket",
    "resolvedTicket",
  ],

  // app/dashboard/chat/page.tsx + [nodeId] (ChatsPage/ChatPage via
  // ChatSidebar, CurrentChat, ChatSidebarItem).
  dashboardChat: [
    "searchOrStartNewChat",
    "support",
    "noChatYetMessage",
    "missingMessageOrFileErrorMessage",
    "sendMessage",
    "writeYourMessage",
    "chat",
    "closeChat",
    "noMessagesYet",
    "selectAChatFirstMessage",
    "status",
  ],

  // app/book/page.tsx (BookingPage2: DoctorBooking/ClinicBooking/
  // PharmacyBooking tabs + their shared filter/results/card/session-selector
  // components). Large because this is genuinely one big page — the doctor/
  // clinic/pharmacy search-and-filter experience. Includes several keys
  // that are only ever looked up dynamically, through enum arrays
  // (doctorSessionTypes, doctorProfileTiers, genders, bookingSorts) rather
  // than as string literals — found by tracing getContent(variable) calls,
  // not just grepping for getContent("literal").
  booking: [
    "filters",
    "deleteAll",
    "searchByMap",
    "bookingTitle",
    "bookingSubTitle",
    "bookingSearchPlaceholder",
    "advancedSearch",
    "previewInMap",
    "geospetialPositoin",
    "applyFilter",
    "sortBy",
    "Best",
    "Worst",
    "MostRecommended",
    "LeastRecommended",
    "today",
    "tomorrow",
    "selectSessionTime",
    "selectFromOtherTimes",
    "seeDoctorProfile",
    "confirmAndContinue",
    "usersSuggestionRate",
    "succeededAppointmentsCount",
    "commentCount",
    "selectClinicCategory",
    "selectSessionType",
    "selectOnMap",
    "province",
    "selectProvince",
    "city",
    "selectCity",
    "district",
    "selectDistrict",
    "category",
    "selectSpecilitis",
    "disease",
    "selectDiseases",
    "service",
    "selectServices",
    "textChat",
    "sipCall",
    "voiceCall",
    "videoCall",
    "inPerson",
    "reportProblem",
    "share",
    "xProductsRegisteredInPharmacy",
    "seeProducts",
    "seeOnMap",
    "seeServices",
    "services",
    "reservation",
    "seeProfile",
    "unset",
    "onlyAvailable",
    "onlyWithEPresc",
    "selectClinicsPlaceholder",
    "specialityGroup",
    "details",
    "educationLevel",
    "selectEducation",
    "gender",
    "selectGender",
    "sessionDate",
    "from",
    "to",
    "sessionTime",
    "expert",
    "specialist",
    "superSpecialist",
    "male",
    "female",
    "availableSessionsCount",
    "onlineConsult",
    "address",
    "more",
    "availableSessionCount",
    "moreSessions",
    "doctorNotAvailableMessage",
    "searchPharmacies",
    "products",
    "selectCategory",
    "missingSessionChoiceErrorMessage",
    "missingSessionKindErrorMessage",
    "selectKind",
    "submit",
    "noSessionAvailableForSelectedPeriodMessage",
  ],

  // app/book/finalize/[nodeId]/page.tsx (FinalizeBookingPage) — the
  // checkout/consent/payment step after a session is chosen. Separate
  // namespace from "booking" since it's a distinct route with mostly
  // non-overlapping keys.
  bookingFinalize: [
    "addRelative",
    "nationalCode",
    "dateOfBirth",
    "phoneNumber",
    "submit",
    "selectPatient",
    "reserveBookingForOther",
    "iConsentToPolicy",
    "previousStage",
    "consentFirst",
    "confirmAndContinue",
    "selectSessionType",
    "checkInput",
    "paymentDetails",
    "tax",
    "freeOfCharge",
    "downPayment",
    "totalPrice",
    "paymentMethod",
    "balance",
    "importantTips",
    "bookingTip1",
    "bookingTip2",
    "payAndReserveBooking",
    "sessionOffice",
    "sessionTime",
    "shiftDoesNotExist",
    "textChat",
    "sipCall",
    "voiceCall",
    "videoCall",
    "inPerson",
    "wallet",
    "xMinutes",
    "xToman",
  ],

  // app/book/page/[page]/page.tsx (BookingPage) — the older/simpler
  // paginated booking list. app/book/page.tsx no longer renders this
  // component (it imports BookingPage but only uses BookingPage2), so this
  // route may be dead; still scoped it since it's reachable. Reuses
  // "doctorsList" since it renders the same DoctorCardWithSessions /
  // DoctorsCardList components as the public doctors list.
  bookingLegacyList: ["booking"],

  // app/become/page.tsx (BecomeSomethingPage) — the public, tab-based page
  // where a visitor picks which node they want to become (doctor, para
  // clinic, clinic, insurance, pharmacy) and submits that node's own become
  // request form. Tab content is the existing per-node Become*Page
  // components (BecomeADoctorPage, BecomeParaClinicPage, BecomeClinicPage,
  // BecomeInsurancePage, BecomePharmacyPage), scoped separately wherever
  // they're already used from within their panel layouts.
  becomeSomething: [
    "becomeSomethingPageTitle",
    "becomeSomethingPageLegend",
    "home",
    "doctor",
    "paraClinic",
    "clinic",
    "insurance",
    "pharmacy",
  ],

  // Components/_Common/SecretaryManager/* — the shared secretary-management
  // UI (secretaries tab, access levels tab, incoming requests tab) reused
  // identically by app/{insurancepanel,clinicpanel,pharmacypanel,
  // doctorpanel}/secretary/page.tsx. Includes access-level category/action
  // keys (clinic/calendar/settings + the read/mutate action keys) which are
  // only reachable dynamically through doctorSecretaryActionCategories /
  // categorizedDoctorSecretaryActions — currently only populated for
  // "doctor", the other node types have empty category/action lists so
  // those code paths never actually request a key today.
  secretaryManager: [
    "dashboard",
    "secretaries",
    "accessLevels",
    "secretaryRequests",
    "displayName",
    "phone",
    "accessLevel",
    "notAssigned",
    "actions",
    "newItem",
    "submittedAt",
    "status",
    "message",
    "name",
    "isDefault",
    "no",
    "yes",
    "submit",
    "cancel",
    "close",
    "deleteSecretaryAccessLevelConfirmationMessage",
    "editAccessLevel",
    "createAccessLevel",
    "Pending",
    "Approved",
    "Rejected",
    "clinic",
    "calendar",
    "settings",
    "clinicAddition",
    "joinClinic",
    "leaveClinics",
    "mutateJoinClinic",
    "readClinics",
    "readCalendar",
    "mutateCalendar",
    "readSettings",
    "mutateSettings",
  ],

  // app/secretarypanel/* — the secretary's own view of their bosses/requests
  // (SecretaryPanelPage + SecretaryManageBossesPage, reused for
  // doctor/insurance/pharmacy/clinic/paraClinic via a `name` prop).
  secretaryPanelHome: [
    "dashboard",
    "bosses",
    "requests",
    "boss",
    "actions",
    "secretaryIncomingRequests",
    "submittedAt",
    "message",
    "status",
    "secretaryDecideSecretaryRequestStatus",
    "approve",
    "reject",
    "leaveBossConfirmationMessage",
    "Pending",
    "Approved",
    "Rejected",
  ],

  // app/insurancepanel/page.tsx (InsurancePanelHomePage) — currently just a
  // dashboard shell.
  insurancePanelHome: ["dashboard"],

  // app/clinicpanel/page.tsx — dashboard shell.
  clinicPanelHome: ["dashboard"],

  // app/clinicpanel/profile/page.tsx (ClinicManageProfilePage,
  // ClinicManageDetailsTab, ClinicManageLocationTab).
  clinicPanelProfile: [
    "dashboard",
    "profile",
    "details",
    "location",
    "missingLocationErrorMessage",
    "selectProvince",
    "selectCity",
    "selectDistrict",
    "submit",
    "name",
    "image",
    "description",
    "summary",
    "category",
    "tags",
    "establishment",
    "businessTime",
    "phone",
    "mail",
    "website",
    "roundTheClock",
    "personelCount",
    "services",
    "certificates",
    "insurances",
    "address",
  ],

  // app/clinicpanel/prescription/page.tsx (ClinicManagePrescriptionsPage +
  // PrescriptionsList).
  clinicPanelPrescription: [
    "dashboard",
    "prescriptions",
    "checkInput",
    "patientNationalCode",
    "trackingCode",
    "submit",
    "techMDID",
    "patientMobile",
    "cancel",
    "clinicServiceName",
    "taminParType",
    "price",
    "2kPrice",
    "subsidyPrice",
    "requestedQuantity",
    "maximumQuantity",
    "remainingQuantity",
    "selection",
    "is2k",
    "fillingCount",
    "taminPrescriptionId",
    "doctorMedicalSystemCode",
    "doctorName",
    "doctorSpeciality",
    "prescriptionDate",
    "actions",
  ],

  // app/clinicpanel/tamin/page.tsx (ClinicTaminCbPage).
  clinicPanelTamin: ["dashboard", "tamin"],

  // app/doctorpanel/clinic/page.tsx (DoctorManageClinicsPage +
  // DoctorClinicsTab/DoctorClinicAdditionsTab/DoctorJoinClinicsTab and their
  // popups). status is looked up dynamically via getContent(node.status)
  // (Pending/Approved/Rejected/Proccessing/Done) rather than as a literal —
  // found by tracing the two Persian status dicts here back to their real
  // usage, which turned out to be Admin-panel-only (out of scope); the
  // DoctorPanel components themselves already look up status correctly
  // through contentKeys.
  doctorPanelClinic: [
    "dashboard",
    "clinics",
    "doctorClinics",
    "doctorJoinClinics",
    "clinicAdditionRequests",
    "clinicsList",
    "clinicName",
    "department",
    "noDepartment",
    "actions",
    "checkInput",
    "ownerName",
    "ownerPhone",
    "province",
    "city",
    "clinicAddress",
    "description",
    "leaveClinicConfirmationMessage",
    "resubmitJoinClinicRequestConfirmationMessage",
    "joinClinicRequest",
    "clickToRequestAddClinic",
    "message",
    "submitRequest",
    "newItem",
    "submittedAt",
    "status",
    "submissionParty",
    "doctor",
    "clinic",
    "statusLastChangedAt",
    "Pending",
    "Approved",
    "Rejected",
    "Proccessing",
    "Done",
  ],

  // app/doctorpanel/page.tsx (DoctorPanelPage) — just the panel shell/sidebar.
  doctorPanelHome: ["dashboard"],

  // app/doctorpanel/calendar/page.tsx + [stamp] (DoctorManageCalendarPage,
  // DoctorManageCalendarDayPage, DoctorCalendarDay, MutateSessionPopup,
  // DeleteSessionPopup, AddSessionsAgent). Session kind/patient-status keys
  // are looked up dynamically via doctorSessionTypes/patientStatuses.
  doctorPanelCalendar: [
    "dashboard",
    "bookingCalendar",
    "availableSessionsCount",
    "reservedSessionsCount",
    "noSessionKindFoundError",
    "invalidSessionDurationError",
    "sessionBoundaries",
    "sessionsKind",
    "description",
    "cancel",
    "submit",
    "sessionDeletionConfirmationMessage",
    "noSelectedDaysError",
    "startSameAsEndError",
    "gapTooLongError",
    "durationTooLongError",
    "noPatientStatusError",
    "noClinicErrorMessage",
    "selectedDays",
    "record",
    "businessTimes",
    "sessionDuration",
    "sessionsGap",
    "patientStatus",
    "availableClinics",
    "submitSessions",
    "newItem",
    "timeLine",
    "sessionStart",
    "sessionEnd",
    "yes",
    "no",
    "office",
    "bookingStatus",
    "notBooked",
    "actions",
    "textChat",
    "sipCall",
    "voiceCall",
    "videoCall",
    "inPerson",
    "oldPatient",
    "newPatient",
  ],

  // app/doctorpanel/settings/page.tsx (DoctorManageSettingsPage + SettingsTab).
  doctorPanelSettings: [
    "dashboard",
    "settings",
    "price",
    "active",
    "hidePrice",
    "callReceiver",
    "textChat",
    "sipCall",
    "voiceCall",
    "videoCall",
    "inPerson",
  ],

  // app/doctorpanel/insurance/page.tsx (DoctorManageInsurancesPage,
  // DoctorInsurancesTab, DoctorInsuranceAdditionRequestsTab,
  // NewInsuranceAdditionRequestPopup, AddInsurancePopup,
  // DeleteInsurancePopup). status reuses AdditionRequestStatus
  // (Pending/Proccessing/Done/Rejected), same enum as Clinic.
  doctorPanelInsurance: [
    "dashboard",
    "insurances",
    "insuranceName",
    "description",
    "sureDeleteInsurance",
    "insuranceAdditionRequests",
    "newItem",
    "submittedAt",
    "status",
    "actions",
    "checkInput",
    "addInsurance",
    "clickToRequestAddInsurance",
    "insurance",
    "submit",
    "cancel",
    "Pending",
    "Proccessing",
    "Done",
    "Rejected",
  ],

  // app/doctorpanel/pharmacy/page.tsx (DoctorManagePharmaciesPage,
  // DoctorPharmaciesTab, DoctorPharmacyRequestsTab,
  // SubmitPharmacyAdditionRequestPopup, DoctorAddPharmacyPopup,
  // DeleteDoctorPharmacyPopup). status reuses AdditionRequestStatus too.
  doctorPanelPharmacy: [
    "dashboard",
    "phrmaciesAndLabs",
    "pharmacies",
    "pharmacyAdditionRequests",
    "newPharmacyAdditionRequest",
    "pharmacyName",
    "province",
    "city",
    "pharmacyAddress",
    "description",
    "submit",
    "cancel",
    "submittedAt",
    "address",
    "status",
    "newItem",
    "actions",
    "checkInput",
    "addPharmacy",
    "clickToRequestAddPharmacy",
    "sureDeletePharmacy",
    "Pending",
    "Proccessing",
    "Done",
    "Rejected",
  ],

  // app/doctorpanel/profile/page.tsx (DoctorManageProfilePage + its tabs:
  // Details, Location, Gallery, SocialMedia, Faq, and their mutate/delete
  // popups). gender options looked up dynamically via genders (male/female).
  doctorPanelProfile: [
    "dashboard",
    "profile",
    "details",
    "gallery",
    "location",
    "socialMedias",
    "faqs",
    "firstName",
    "lastName",
    "ssid",
    "gender",
    "mcCode",
    "medicalSystemCode",
    "avatar",
    "mainSpeciality",
    "specialities",
    "introduction",
    "services",
    "achivemets",
    "website",
    "landLine",
    "address",
    "sureDeleteGalleryItem",
    "newItem",
    "question",
    "answer",
    "isActive",
    "order",
    "actions",
    "alt",
    "description",
    "image",
    "sureDeleteFaq",
    "socialMediaName",
    "socialMediaLink",
    "sureDeleteSocialMediaMessage",
    "missingLocationErrorMessage",
    "selectProvince",
    "selectCity",
    "selectDistrict",
    "submit",
    "male",
    "female",
  ],

  // app/doctorpanel/patient/page.tsx + [nodeId]/(profile|vital) —
  // DoctorManagePatientsPage/Patient/ProfilePage/VitalsPage, PatientFiles,
  // NewPatientFilePopup, NewPatientProfileRecordPopup,
  // PreviewPatientProfileRecordPopup.
  doctorPanelPatient: [
    "dashboard",
    "patients",
    "attachments",
    "view",
    "patientFiles",
    "newPatientFile",
    "createdAt",
    "doctor",
    "title",
    "diagnosis",
    "actions",
    "description",
    "isRecordPublic",
    "patientProfileRecordAttachments",
    "patientProfileRecords",
    "newPatientProfileRecord",
    "patientAdditionDate",
    "username",
    "fullName",
    "notAssigned",
    "phoneNumber",
  ],

  // app/doctorpanel/office/page.tsx + [nodeId] (DoctorManageOfficesPage,
  // DoctorManageOfficePage, DoctorManageOfficeLocationTab,
  // DoctorMutateOfficePopup, DeleteOfficePopup).
  doctorPanelOffice: [
    "dashboard",
    "office",
    "offices",
    "newItem",
    "name",
    "address",
    "telephone",
    "order",
    "isActive",
    "actions",
    "details",
    "location",
    "submit",
    "sureDeleteOffice",
  ],

  // app/doctorpanel/tamin/page.tsx (TaminCbPage).
  doctorPanelTamin: ["dashboard", "tamin"],

  // app/doctorpanel/drug/page.tsx (DoctorManagePrescriptionsPage — the
  // prescriptions/drugs list, despite the route being named "drug") +
  // LoadPrescriptionsFromTamin.
  doctorPanelPrescriptionList: [
    "dashboard",
    "drugsAndPrescriptions",
    "prescriptions",
    "visitPrescriptions",
    "referralPrescriptions",
    "committedTaminPrescriptions",
    "prescriptionType",
    "taminPrescriptionId",
    "taminPrescriptionTracking",
    "prescriptionsList",
    "newPrescription",
    "loadPrescriptionsFromTamin",
    "createdAt",
    "patientName",
    "patientNationalCode",
    "taminPrescriptionsCount",
    "actions",
    "prescriptionDetails",
    "sureDeleteVisitPrescription",
    "taminId",
    "trackingCode",
    "message",
    "quantity",
    "referralSpeciality",
    "referralDate",
    "referralPrescriptionComplaints",
    "referralPrescriptionIcds",
  ],

  // app/doctorpanel/prescription/[nodeId]/edit/page.tsx
  // (DoctorEditPrescriptionPage). Note: the old Prescription/Create and
  // Prescription/Overview subtrees are dead code (both their routes render
  // the Prescription2 equivalents instead — see the commented-out imports in
  // app/doctorpanel/prescription/page.tsx and .../[nodeId]/page.tsx), so
  // they're intentionally skipped here.
  doctorPanelPrescriptionEdit: [
    "dashboard",
    "drugsAndPrescriptions",
    "editDraftPrescription",
  ],

  // app/doctorpanel/prescription/[nodeId]/print/page.tsx
  // (PrintPrescriptionPage).
  doctorPanelPrescriptionPrint: [
    "patientName",
    "trackingCode",
    "taminId",
    "medications",
  ],

  // app/doctorpanel/prescription/page.tsx (CreatePrescriptionPage) and
  // app/doctorpanel/prescription/[nodeId]/page.tsx
  // (PreviewPrescription2Page, which just renders CreatePrescriptionPage
  // with a defaultValue) — the whole Prescription2/* tree: Prescription2Agent,
  // ReferralPrescription, and the UI/* patient-selector/drug-item/actions
  // components.
  doctorPanelPrescriptionCreate: [
    "dashboard",
    "drugsAndPrescriptions",
    "makeVisitPrescription",
    "checkInput",
    "referreeSpeciality",
    "referralPrescriptionComplaints",
    "referralPrescriptionIcds",
    "description",
    "quantity",
    "referralDate",
    "submitReferralPrescription",
    "cancel",
    "referralPrescription",
    "createNewPrescription",
    "addPatient",
    "selectPatientLegend",
    "badNationalIdErrorMessage",
    "patientNationalId",
    "inquiryPatient",
    "patientNotFoundErrorMessage",
    "searchDrugNameOrCode",
    "drugNameOrCode",
    "draftingEmptyPrescriptionErrorMessage",
    "drugCount",
    "testDoDate",
    "startAgain",
    "addDrug",
    "drugInstruction",
    "drugAmount",
    "dateDo",
    "noUserSelectedLegend",
    "patientDetails",
    "insuranceType",
    "nationalCode",
    "moblieNumber",
    "commitPrescription",
    "draftPrescription",
    "editPrescription",
    "enableEditPrescriptionMode",
    "disableEditPrescriptionMode",
    "deletePrescription",
    "notAssigned",
    "committedTaminPrescriptions",
    "hasTaminPrivilege",
    "noTaminPrivilege",
    "inquiryTaminPrivilege",
    "male",
    "female",
  ],

  // app/doctorpanel/shift/page.tsx (DoctorManageShiftsPage, ShiftItem,
  // Replicator, ShiftsPreview, DayShifts, useShiftUtils). sessionType/
  // patientType options reuse doctorSessionTypes/patientStatuses.
  doctorPanelShift: [
    "dashboard",
    "shifts",
    "shiftStartMustBeBeforeEnd",
    "missingShiftOffice",
    "missingShiftPatientStatus",
    "missingShiftSessionType",
    "shiftIsEmpty",
    "understood",
    "deleteShift",
    "startTime",
    "endTime",
    "office",
    "sessionDuration",
    "sessionsGap",
    "sessionType",
    "patientType",
    "checkInput",
    "shiftsOverlap",
    "offDay",
    "saveAndPublish",
    "previewXDayOfWeekShifts",
    "thisDayIsOff",
    "applyTheseSettingsOnDesiredDays",
    "selectTargetWeekDays",
    "selectAll",
    "removeAll",
    "cancel",
    "modificationsApplied",
    "applySettingsOnXDays",
    "shiftsProTip",
    "newShift",
    "addANewShift",
    "textChat",
    "sipCall",
    "voiceCall",
    "videoCall",
    "inPerson",
    "oldPatient",
    "newPatient",
  ],

  // The 7 doctorpanel stub pages (article/chat/discount/document/license/
  // offer/finance) — each just renders a breadcrumb + placeholder <p>, no
  // real content yet. One shared namespace since they're trivial.
  doctorPanelStub: [
    "dashboard",
    "articles",
    "chatWithPatients",
    "discounts",
    "patientDocuments",
    "licenses",
    "offers",
    "financialMangement",
  ],

  // app/doctorpanel/schedule/page.tsx (DoctorManageSchedulePage,
  // ScheduleBookingCard).
  doctorPanelSchedule: [
    "dashboard",
    "schedule",
    "nothingFound",
    "view",
    "bookedAt",
    "textChat",
    "sipCall",
    "voiceCall",
    "videoCall",
    "inPerson",
  ],

  // app/doctorpanel/service/page.tsx + [nodeId] (DoctorManageServicesPage,
  // DoctorManageServicePage, DoctorMutateServicePopup, DeleteServicePopup).
  doctorPanelService: [
    "dashboard",
    "services",
    "name",
    "category",
    "price",
    "discount",
    "inventory",
    "order",
    "isActive",
    "actions",
    "newItem",
    "isHome",
    "special",
    "image",
    "sameAs",
    "description",
    "whyChoose",
    "stages",
    "results",
    "sureDeleteService",
  ],

  // app/doctorpanel/servicepackage/page.tsx + [nodeId]
  // (DoctorManageServicePackagesPage, DoctorManageServicePackagePage,
  // DoctorMutateServicePackagePopup, DeleteServicePackagePopup).
  doctorPanelServicePackage: [
    "dashboard",
    "servicePackages",
    "name",
    "category",
    "services",
    "price",
    "discount",
    "order",
    "isActive",
    "actions",
    "newItem",
    "image",
    "sameAs",
    "summary",
    "description",
    "whyChoose",
    "stages",
    "results",
    "sureDeleteServicePackage",
  ],

  // app/pharmacypanel/page.tsx (PharmacyPanelPage) — just the panel shell.
  pharmacyPanelHome: ["dashboard"],

  // app/pharmacypanel/prescription/page.tsx (PharmacyFillPrescriptionPage +
  // its 3 tabs: FindPrescriptionAgent, PharmacyPrescriptionCache,
  // PharmacyFilledPrescriptions — plus PrescriptionList/PrescriptionFiller/
  // PrescriptionListItem, which FindPrescriptionAgent renders once a
  // prescription is found).
  pharmacyPanelPrescription: [
    "dashboard",
    "prescriptions",
    "findPrescription",
    "pharmacyPrescriptionsCache",
    "filledPrescriptions",
    "unknownErrorOccured",
    "fillingPrescription",
    "fillPrescriptionLegend",
    "searchForPrescription",
    "activePrescriptions",
    "cancel",
    "prescriptionId",
    "doctorName",
    "prescriptionDate",
    "fillingEmptyPrescriptionError",
    "checkInput",
    "selectedPrescription",
    "back",
    "drugName",
    "prescribedCount",
    "remainingDrugCount",
    "availbaleDrugCount",
    "unitPrice",
    "totalLinearPrice",
    "drugForm",
    "drugInstruction",
    "confirmation",
    "confirmed",
    "actions",
    "replaceDrug",
    "sendToTamin",
    "prescriptionItems",
    "prescriptionDetailId",
    "drugCode",
    "prescriptionInsuranceStatus",
    "prescriptionRequiresBarcodeInquiry",
    "prescriptionHospitalDrug",
    "prescriptionMaxAge",
    "doctorMedicalSystemCode",
    "doctorSpeciality",
    "patientFirstName",
    "patientLastName",
    "custName",
    "prescriptionComments",
    "referReason",
    "prescriptionElectronicFlag",
    "prescriptionClinicDoc",
    "prescriptionTime",
    "prescriptionSpecCode",
    "prescriptionItemsCount",
    "taminPrescriptionId",
    "submittedAt",
    "requestId",
    "requestPrice",
    "regdate",
    "pharmacyRequestPrice",
    "isNotePatient",
    "itemsCount",
  ],

  // app/pharmacypanel/filledPrescription/[nodeId]/page.tsx
  // (FilledPrescriptionPage).
  pharmacyPanelFilledPrescription: [
    "dashboard",
    "prescriptions",
    "filledPrescription",
    "submittedAt",
    "prescription",
    "requestId",
    "requestPrice",
    "regdate",
    "pharmacyRequestPrice",
    "isNotePatient",
    "doctorMedicalSystemCode",
    "doctorFirstName",
    "doctorLastName",
    "userId",
    "phaId",
    "month",
    "year",
    "prescriptionDate",
    "patientAmount",
    "custServiceType",
    "doctorSpeciality",
    "custServiceTypeDesc",
    "drugCode",
    "drugName",
    "drugCount",
    "itemPrice",
    "franshiz",
    "pharmacyItemPrice",
    "timesADay",
    "dose",
    "subsidyPrice",
    "patientPrice",
    "supportSpecialPatient",
    "total",
    "sumIsNotePatient",
  ],

  // app/pharmacypanel/tamin/page.tsx (PharmacyTaminPage + its 4 tabs:
  // DoctorTaminTokenManager [shared with doctorpanel, no getContent calls of
  // its own], GetPharmacyPrescription, GetSubmittedPrescInfo,
  // GetAdditiveDrugs [no getContent calls]).
  pharmacyPanelTamin: [
    "dashboard",
    "tamin",
    "precriptionFiller",
    "taminToken",
    "getPrescription",
    "getSubmittedPrescriptionInfo",
    "additiveDrugs",
    "prescriptionSubmitted",
    "back",
    "remove",
    "requestId",
    "requestPrice",
    "pharmacyRequestPrice",
    "isNotePatient",
    "patientPrice",
    "drugCode",
    "drugName",
    "drugCount",
    "itemPrice",
    "franchiz",
    "pharmacyItemPrice",
    "timesADay",
    "dose",
    "subsidyPrice",
    "supportSpecialPatient",
    "sumPrice",
    "sumIsNotePatient",
    "reason",
    "prescriptionItems",
    "precheckPresc",
    "submitPresc",
    "referrPrescription",
    "drugForm",
    "prescribedCount",
    "remainingDrugCount",
    "drugInstruction",
    "selection",
    "requestedQuantity",
    "price",
    "prescriptionsList",
    "headPrescId",
    "prescDate",
    "docId",
    "docSpec",
    "patientFirstName",
    "patientLastName",
    "clinicDoc",
    "prescTime",
    "specCode",
    "itemsCount",
    "actions",
    "patientNationalCode",
    "trackingCode",
    "unknownErrorOccured",
  ],

  // app/pharmacypanel/product/page.tsx (PharmacyProductsPage — available
  // products to add + my products tabs).
  pharmacyPanelProduct: [
    "dashboard",
    "products",
    "price",
    "discount",
    "isActive",
    "freeDelivery",
    "fastDelivery",
    "sureDeleteMyProduct",
    "availableProducts",
    "name",
    "category",
    "unset",
    "basePrice",
    "actions",
    "addProduct",
    "myProducts",
    "special",
  ],

  // app/pharmacypanel/productPackage/page.tsx
  // (PharmacyManageProductPackagesPage).
  pharmacyPanelProductPackage: [
    "dashboard",
    "productPackages",
    "name",
    "category",
    "image",
    "products",
    "price",
    "discount",
    "summary",
    "description",
    "whyChoose",
    "order",
    "isActive",
    "sureDeleteProductPackage",
    "newItem",
    "unset",
    "actions",
  ],
} as const satisfies Record<string, readonly ContentKey[]>;

export type ContentNamespace = keyof typeof contentNamespaces;

// Flattens one or more namespaces into a deduped list of ContentKeys, e.g.
// getNamespaceKeys(["common", "home"]).
export const getNamespaceKeys = (
  namespaces: ContentNamespace[],
): ContentKey[] => {
  const set = new Set<ContentKey>();
  for (const ns of namespaces) {
    for (const key of contentNamespaces[ns]) set.add(key);
  }
  return Array.from(set);
};
