import { ContentNamespace } from "./contentNamespaces";

// Maps each ContentNamespace to the public route(s) that actually render it.
// Derived by grepping every getScopedTextContent(...) / LocaleScopeProvider
// namespaces={...} call site (see contentNamespaces.tsx for the keys each
// namespace groups). Used only by the admin text-content table to link a key
// to the page(s) it's scoped to — no page imports this itself.
//
// "common" is intentionally left out: it's shared sitewide chrome (header/
// footer/shared UI), not tied to one route, so it's rendered without a link
// wherever this map is consumed instead of pointing at an arbitrary page.
//
// Dynamic segments ([nodeId], [page], [stamp]) are stripped down to their
// nearest static parent route, since there's no real id to link to from an
// admin content-key list.
export const namespaceRoutes: Partial<Record<ContentNamespace, string[]>> = {
  home: ["/"],
  doctorsList: ["/doctors"],
  diseasesList: ["/disease"],
  drugsList: ["/drug"],
  symptomsList: ["/symptom"],

  dashboardHome: ["/dashboard"],
  dashboardInvoice: ["/dashboard/invoice"],
  dashboardTransaction: ["/dashboard/transaction"],
  dashboardOrder: ["/dashboard/order"],
  dashboardAddress: ["/dashboard/address"],
  patientInsurance: ["/dashboard/insurance"],
  dashboardBooking: ["/dashboard/booking"],
  dashboardVital: ["/dashboard/vital"],
  dashboardNotification: ["/dashboard/notification"],
  dashboardSupport: ["/dashboard/support"],
  doctorPanelNetwork: ["/doctorpanel/network"],
  providerHome: ["/clinicpanel", "/hospitalpanel", "/pharmacypanel", "/paraClinicPanel", "/insurancepanel"],
  centerDoctors: ["/clinicpanel", "/clinicpanel/doctor", "/hospitalpanel", "/hospitalpanel/doctor"],
  dashboardChat: ["/dashboard/chat", "/doctorpanel/chat"],

  booking: ["/book"],
  bookingFinalize: ["/book/finalize"],
  bookingFlow: ["/book/finalize", "/dr", "/book", "/dashboard/booking"],

  becomeSomething: ["/become"],

  secretaryManager: [
    "/clinicpanel/secretary",
    "/insurancepanel/secretary",
    "/pharmacypanel/secretary",
    "/doctorpanel/secretary",
    "/hospitalpanel/secretary",
    "/paraClinicPanel/secretary",
  ],
  secretaryPanelHome: [
    "/secretarypanel",
    "/secretarypanel/pharmacy",
    "/secretarypanel/paraClinic",
    "/secretarypanel/insurance",
    "/secretarypanel/doctor",
    "/secretarypanel/clinic",
    "/secretarypanel/hospital",
  ],

  insurancePanelHome: ["/insurancepanel"],

  clinicPanelHome: ["/clinicpanel"],
  clinicPanelProfile: ["/clinicpanel/profile"],
  clinicPanelPrescription: ["/clinicpanel/prescription"],
  clinicPanelTamin: ["/clinicpanel/tamin"],

  hospitalPanelHome: ["/hospitalpanel"],
  hospitalPanelProfile: ["/hospitalpanel/profile"],

  doctorPanelHome: ["/doctorpanel"],
  doctorPanelClinic: ["/doctorpanel/clinic"],
  doctorPanelHospital: ["/doctorpanel/hospital"],
  doctorPanelCalendar: ["/doctorpanel/calendar"],
  doctorPanelSettings: ["/doctorpanel/settings"],
  doctorPanelInsurance: ["/doctorpanel/insurance"],
  doctorPanelPharmacy: ["/doctorpanel/pharmacy"],
  doctorPanelProfile: ["/doctorpanel/profile"],
  doctorPanelPatient: ["/doctorpanel/patient"],
  doctorPanelOffice: ["/doctorpanel/office"],
  doctorPanelTamin: ["/doctorpanel/tamin"],
  doctorPanelPrescriptionList: ["/doctorpanel/drug"],
  doctorPanelPrescriptionEdit: ["/doctorpanel/prescription"],
  doctorPanelPrescriptionPrint: ["/doctorpanel/prescription"],
  doctorPanelPrescriptionCreate: ["/doctorpanel/prescription"],
  doctorPanelShift: ["/doctorpanel/shift"],
  doctorPanelStub: [
    "/doctorpanel/article",
    "/doctorpanel/discount",
    "/doctorpanel/document",
    "/doctorpanel/license",
    "/doctorpanel/offer",
    "/doctorpanel/finance",
  ],
  doctorPanelSchedule: ["/doctorpanel/schedule"],
  doctorPanelService: ["/doctorpanel/service"],
  doctorPanelServicePackage: ["/doctorpanel/servicepackage"],
  doctorPanelOrder: ["/doctorpanel/order"],

  pharmacyPanelHome: ["/pharmacypanel"],
  pharmacyPanelProfile: ["/pharmacypanel/profile"],
  pharmacyPanelPrescription: ["/pharmacypanel/prescription"],
  pharmacyPanelFilledPrescription: ["/pharmacypanel/filledPrescription"],
  pharmacyPanelTamin: ["/pharmacypanel/tamin"],
  pharmacyPanelProduct: ["/pharmacypanel/product"],
  pharmacyPanelProductPackage: ["/pharmacypanel/productPackage"],
  pharmacyPanelOrder: ["/pharmacypanel/order"],

  // ---- useScopedLocale migration, 2026-09 ----
  mapPage: ["/map"],
  adminPushTest: ["/[adminKey]/pushTest"],
  doctorPanelPrescriptionDrugItem: ["/doctorpanel/prescription"],
  doctorPanelPrescriptionEditor: ["/doctorpanel/prescription"],
  doctorPanelShiftUtils: ["/doctorpanel/shift"],
  doctorPanelBecomeDoctor: ["/become/doctor", "/doctorpanel"],
  pharmacyPanelCurrentLicenseWidget: ["/pharmacypanel"],
  dashboardUserIdentity: ["/dashboard"],
  dashboardEditUserDetailsPopup: ["/dashboard"],
  dashboardUserVitals: ["/dashboard"],
  dashboardUserMedicalDetails: ["/dashboard"],
  dashboardMutateUserMedicalPopup: ["/dashboard"],
  dashboardVitalList: ["/dashboard/vital"],
  dashboardAddVitalPopup: ["/dashboard/vital"],
  dashboardMutateAddressPopup: ["/dashboard/address"],
  dashboardReservationStatusBadge: ["/dashboard/booking"],
  dashboardReservationTimeline: ["/dashboard/booking"],
  dashboardReservationJoinButton: ["/dashboard/booking"],
  dashboardOrderStatusBadge: ["/dashboard/order"],
  dashboardUserManageCall: ["/call"],
  paraClinicPanelHome: ["/paraClinicPanel"],
  paraClinicPanelLicense: ["/paraClinicPanel/license"],
  paraClinicPanelArticle: ["/paraClinicPanel/article"],
  paraClinicPanelOrder: ["/paraClinicPanel/order"],
  paraClinicPanelProfile: ["/paraClinicPanel/profile"],
  paraClinicPanelTamin: ["/paraClinicPanel/tamin"],
  paraClinicPanelTest: ["/paraClinicPanel/test"],
  medicalCenter: ["/clinic", "/hospital"],
  medicalCenterNav: ["/clinic", "/hospital", "/insurance", "/paraClinic"],
  medicalCenterLocation: ["/clinic", "/hospital", "/insurance", "/paraClinic"],
  centreCard: ["/clinic", "/hospital", "/paraClinic", "/pharmacy", "/test", "/map", "/book", "/disease", "/insurancepanel"],
  insuranceCard: ["/insurance"],
  openingHours: ["/pharmacy", "/paraClinic", "/clinic", "/hospital", "/map"],
  clinicsList: ["/clinic"],
  clinicPage: ["/clinic"],
  hospitalsList: ["/hospital"],
  hospitalPage: ["/hospital"],
  insurancesList: ["/insurance"],
  insurancePage: ["/insurance"],
  paraClinicsList: ["/paraClinic"],
  paraClinicPage: ["/paraClinic"],
  cartPage: ["/cart"],
  cartCheckoutPopup: ["/cart"],
  paymentResult: ["/payment"],
  onlinePayment: ["/payment", "/dashboard/transaction", "/cart"],
  orderConfirmation: ["/order"],
  productCartable: ["/product", "/productPackage", "/service", "/servicePackage"],
  productServiceSwitch: ["/product", "/service"],
  productPackagePage: ["/productPackage"],
  servicePackagePage: ["/servicePackage"],
  // Existing (previously empty) namespaces that now have keys.
  products: ["/product"],
  services: ["/service"],
  aboutPage: ["/about"],
  blogMainCard: ["/mag", "/"],
  magPost: ["/mag"],
  contactPage: ["/contact"],
  diseasePage: ["/disease"],
  diseaseCard: ["/disease"],
  doctorPage: ["/doctor"],
  drProfile: ["/dr"],
  drBookingSidebar: ["/dr", "/book/finalize"],
  drSessions: ["/dr"],
  drSelectClinicFirstPopup: ["/dr"],
  drugCard: ["/drug", "/disease"],
  drugPage: ["/drug"],
  faqPage: ["/faq"],
  homeFaqs: ["/", "/faq"],
  onboardingPage: ["/onboarding"],
  policyPage: ["/policy", "/privacy"],
  specialitiesList: ["/speciality"],
  specialityCard: ["/speciality", "/disease"],
  specialityPage: ["/speciality"],
  symptomCard: ["/symptom", "/disease"],
  symptomPage: ["/symptom"],
  testCard: ["/test"],
  testsList: ["/test"],
  wizardPage: ["/wizard"],
  mag: ["/mag"],
};
